lastupdatecheck: 0
recentrepos:
- /home/nick/gem5-yzy
- /home/nick/ysyx-workbench
- /home/nick/FDRA
- /home/nick/.dotfiles/config/nvim/lua/user
- /home/nick/latex
- /home/nick/gem5
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
ignorewhitespaceindiffview: false
